export const GET_USER_TICKET_REQUEST = "USER_TICKET/GET_USER_TICKET_REQUEST";
export const GET_USER_TICKET_SUCCESS = "USER_TICKET/GET_USER_TICKET_SUCCESS";
export const GET_USER_TICKET_FAILURE = "USER_TICKET/GET_USER_TICKET_FAILURE";